name: CI

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main  # Run the workflow on pull requests targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Makefile tasks
      - name: Run Makefile
        run: make